export enum ActionType {
  READ_FILE = "READ_FILE",
  WRITE_FILE = "WRITE_FILE",
  CREATE_FILE = "CREATE_FILE",
  DELETE_FILE = "DELETE_FILE",
  SHELL_EXECUTE = "SHELL_EXECUTE",
  GIT_STATUS = "GIT_STATUS",
  GIT_ADD = "GIT_ADD",
  GIT_COMMIT = "GIT_COMMIT",
  GIT_PUSH = "GIT_PUSH",
  GIT_FORCE_PUSH = "GIT_FORCE_PUSH",
  MCP_TOOL_CALL = "MCP_TOOL_CALL",
  AWS_CLOUDWATCH_READ = "AWS_CLOUDWATCH_READ",
}
