export enum CommandCategory {
  TEST = "TEST",
  LINT = "LINT",
  BUILD = "BUILD",
  PACKAGE_INSTALL = "PACKAGE_INSTALL",
  GIT = "GIT",
  FILESYSTEM_DESTRUCTIVE = "FILESYSTEM_DESTRUCTIVE",
  NETWORK = "NETWORK",
  OTHER = "OTHER",
}
