export enum PolicyField {
  AGENT_TYPE = "AGENT_TYPE",
  ACTION_TYPE = "ACTION_TYPE",
  RESOURCE_TYPE = "RESOURCE_TYPE",
  RESOURCE_IDENTIFIER = "RESOURCE_IDENTIFIER",
  PATH = "path",
  COMMAND_CATEGORY = "COMMAND_CATEGORY",
  BRANCH = "BRANCH",
  TOOL = "TOOL",
  ENVIRONMET = "ENVIRONMET",
}
